SpECTRE: DataVector Class Reference
DataVector Class Reference
Data Structures
A class for storing data on a mesh.
#include <DataVector.hpp>
Public Types
using value_type = double
using allocator_type = std::allocator< value_type >
using size_type = size_t
using difference_type = std::ptrdiff_t
Public Member Functions
DataVector (size_t size, double value=std::numeric_limits< double >::signaling_NaN())
Create with the given size and value.
DataVector (double *start, size_t size)
Create a non-owning DataVector that points to start
DataVector (std::initializer_list< double > list)
Create from an initializer list.
DataVector ()=default
Empty DataVector.
size_t size () const
Number of values stored.
bool is_owning () const
Returns true if the class owns the data.
void pup (PUP::er &p)
Serialization for Charm++.
void set_data_ref (DataVector &rhs)
Set the DataVector to be a reference to another DataVector object.
void set_data_ref (double *start, size_t size)
Set the DataVector to be a reference to another DataVector object.
double & operator[] (const size_type i)
Access ith element.
const double & operator[] (const size_type i) const
Access ith element.
double * data ()
Access to the pointer.
const double * data () const
Access to the pointer.
decltype(auto) begin ()
Returns iterator to beginning of data.
decltype(auto) begin () const
Returns iterator to beginning of data.
decltype(auto) end ()
Returns iterator to end of data.
decltype(auto) end () const
Returns iterator to end of data.
DataVector & operator= (const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator+= (const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator+= (const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator+= (const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator-= (const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator-= (const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator-= (const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator*= (const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator*= (const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator*= (const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator/= (const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
DataVector & operator/= (const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
DataVector & operator/= (const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator+ (const DataVector &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator+ (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator+ (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator+ (const DataVector &lhs, const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator+ (const double &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const DataVector &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator- (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator- (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const DataVector &lhs, const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const double &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator- (const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator* (const DataVector &lhs, const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator* (const double &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator* (const DataVector &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator* (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator* (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator/ (const DataVector &lhs, const double &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend operator/ (const DataVector &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator/ (const blaze::Vector< VT, VF > &lhs, const DataVector &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
template<typename VT , bool VF>
decltype(auto) friend operator/ (const DataVector &lhs, const blaze::Vector< VT, VF > &rhs)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend min (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend max (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend abs (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend sqrt (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend invsqrt (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend cbrt (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend invcbrt (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend pow (const DataVector &t, const double exponent)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend exp (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend exp2 (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend exp10 (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend log (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend log2 (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend log10 (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend sin (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend cos (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend tan (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend asin (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend acos (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend atan (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend sinh (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend cosh (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend tanh (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend asinh (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend acosh (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend atanh (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend erf (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
decltype(auto) friend erfc (const DataVector &t)
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
Detailed Description
A class for storing data on a mesh.
A Data holds an array of contiguous data and can be either owning (the array is deleted when the Data goes out of scope) or non-owning, meaning it just has a pointer to an array.
Member Typedef Documentation
allocator_type
using DataVector::allocator_type = std::allocator<value_type>
difference_type
using DataVector::difference_type = std::ptrdiff_t
size_type
using DataVector::size_type = size_t
value_type
using DataVector::value_type = double
Constructor & Destructor Documentation
DataVector() [1/4]
DataVector::DataVector (size_t size, double value = std::numeric_limits<double>::signaling_NaN()) explicit
Create with the given size and value.
Parameters
size number of values
value the value to initialize each element.
DataVector() [2/4]
DataVector::DataVector (double * start, size_t size)
Create a non-owning DataVector that points to start
References ASSERT, begin(), std::copy(), DataVector(), end(), is_owning(), operator=(), and size().
DataVector() [3/4]
DataVector::DataVector (std::initializer_list< double > list)
Create from an initializer list.
DataVector() [4/4]
DataVector::DataVector () default
Empty DataVector.
Referenced by DataVector(), and erfc().
Member Function Documentation
abs()
decltype(auto) friend DataVector::abs (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
acos()
decltype(auto) friend DataVector::acos (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References acos().
Referenced by acos().
acosh()
decltype(auto) friend DataVector::acosh (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References acosh().
Referenced by acosh().
asin()
decltype(auto) friend DataVector::asin (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References asin().
Referenced by asin().
asinh()
decltype(auto) friend DataVector::asinh (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References asinh().
Referenced by asinh().
atan()
decltype(auto) friend DataVector::atan (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References atan().
Referenced by atan().
atanh()
decltype(auto) friend DataVector::atanh (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References atanh().
Referenced by atanh().
begin() [1/2]
decltype(auto) DataVector::begin () inline
Returns iterator to beginning of data.
Referenced by DataVector(), and operator==().
begin() [2/2]
decltype(auto) DataVector::begin () const inline
Returns iterator to beginning of data.
cbrt()
decltype(auto) friend DataVector::cbrt (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References cbrt().
Referenced by cbrt().
cos()
decltype(auto) friend DataVector::cos (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References cos().
Referenced by cos().
cosh()
decltype(auto) friend DataVector::cosh (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References cosh().
Referenced by cosh().
data() [1/2]
double* DataVector::data () inline
Access to the pointer.
Referenced by set_data_ref().
data() [2/2]
const double* DataVector::data () const inline
Access to the pointer.
end() [1/2]
decltype(auto) DataVector::end () inline
Returns iterator to end of data.
Referenced by DataVector(), and operator==().
end() [2/2]
decltype(auto) DataVector::end () const inline
Returns iterator to end of data.
erf()
decltype(auto) friend DataVector::erf (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References erf().
Referenced by erf().
erfc()
decltype(auto) friend DataVector::erfc (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References ASSERT, DataVector(), erfc(), operator!=(), operator<<(), operator=(), operator==(), pow(), size(), and SPECTRE_ALWAYS_INLINE.
Referenced by erfc().
exp()
decltype(auto) friend DataVector::exp (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References exp().
Referenced by exp().
exp10()
decltype(auto) friend DataVector::exp10 (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References exp10().
Referenced by exp10().
exp2()
decltype(auto) friend DataVector::exp2 (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References exp2().
Referenced by exp2().
invcbrt()
decltype(auto) friend DataVector::invcbrt (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
invsqrt()
decltype(auto) friend DataVector::invsqrt (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
is_owning()
bool DataVector::is_owning () const inline
Returns true if the class owns the data.
Referenced by DataVector().
log()
decltype(auto) friend DataVector::log (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References log().
Referenced by log().
log10()
decltype(auto) friend DataVector::log10 (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References log10().
Referenced by log10().
log2()
decltype(auto) friend DataVector::log2 (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References log2().
Referenced by log2().
max()
decltype(auto) friend DataVector::max (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References max().
Referenced by max().
min()
decltype(auto) friend DataVector::min (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References min().
Referenced by min().
operator*() [1/5]
decltype(auto) friend DataVector::operator* (const DataVector & lhs, const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [2/5]
decltype(auto) friend DataVector::operator* (const double & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [3/5]
decltype(auto) friend DataVector::operator* (const DataVector & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [4/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator* (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*() [5/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator* (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*=() [1/3]
DataVector& DataVector::operator*= (const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator*= (const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator*=() [3/3]
DataVector& DataVector::operator*= (const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [1/5]
decltype(auto) friend DataVector::operator+ (const DataVector & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [2/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator+ (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [3/5]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator+ (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [4/5]
decltype(auto) friend DataVector::operator+ (const DataVector & lhs, const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+() [5/5]
decltype(auto) friend DataVector::operator+ (const double & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+=() [1/3]
DataVector& DataVector::operator+= (const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator+= (const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator+=() [3/3]
DataVector& DataVector::operator+= (const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [1/6]
decltype(auto) friend DataVector::operator- (const DataVector & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [2/6]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator- (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [3/6]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator- (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [4/6]
decltype(auto) friend DataVector::operator- (const DataVector & lhs, const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [5/6]
decltype(auto) friend DataVector::operator- (const double & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-() [6/6]
decltype(auto) friend DataVector::operator- (const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-=() [1/3]
DataVector& DataVector::operator-= (const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator-= (const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator-=() [3/3]
DataVector& DataVector::operator-= (const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [1/4]
decltype(auto) friend DataVector::operator/ (const DataVector & lhs, const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [2/4]
decltype(auto) friend DataVector::operator/ (const DataVector & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [3/4]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator/ (const blaze::Vector< VT, VF > & lhs, const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/() [4/4]
template<typename VT , bool VF> decltype(auto) friend DataVector::operator/ (const DataVector & lhs, const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/=() [1/3]
DataVector& DataVector::operator/= (const DataVector & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/=() [2/3]
template<typename VT , bool VF> DataVector& DataVector::operator/= (const blaze::Vector< VT, VF > & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator/=() [3/3]
DataVector& DataVector::operator/= (const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
operator=()
DataVector& DataVector::operator= (const double & rhs) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
Referenced by DataVector(), and erfc().
operator[]() [1/2]
double& DataVector::operator[] (const size_type i) inline
Access ith element.
References ASSERT.
operator[]() [2/2]
const double& DataVector::operator[] (const size_type i) const inline
Access ith element.
References ASSERT.
pow()
decltype(auto) friend DataVector::pow (const DataVector & t, const double exponent) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References pow().
pup()
void DataVector::pup (PUP::er & p)
Serialization for Charm++.
set_data_ref() [1/2]
void DataVector::set_data_ref (DataVector & rhs) inline
Set the DataVector to be a reference to another DataVector object.
References data(), and set_data_ref().
Referenced by set_data_ref().
set_data_ref() [2/2]
void DataVector::set_data_ref (double * start, size_t size)
Set the DataVector to be a reference to another DataVector object.
References size().
sin()
decltype(auto) friend DataVector::sin (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References sin().
Referenced by sin().
sinh()
decltype(auto) friend DataVector::sinh (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References sinh().
Referenced by sinh().
size()
size_t DataVector::size () const inline
Number of values stored.
Referenced by DataVector(), Basis::lgl::definite_integral(), erfc(), operator==(), and set_data_ref().
sqrt()
decltype(auto) friend DataVector::sqrt (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References sqrt().
Referenced by sqrt().
tan()
decltype(auto) friend DataVector::tan (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References tan().
Referenced by tan().
tanh()
decltype(auto) friend DataVector::tanh (const DataVector & t) inline
See the Blaze library documentation for details on these functions since they merely forward to Blaze. https://bitbucket.org/blaze-lib/blaze/overview.
References tanh().
Referenced by tanh().
The documentation for this class was generated from the following files:
src/DataStructures/DataVector.hpp
src/DataStructures/DataVector.cpp