SpECTRE: StripeIterator Class Reference
StripeIterator Class Reference
Data Structures
Iterates over the 1-dimensional stripes with info on how to iterate over the current stripe.
#include <StripeIterator.hpp>
Public Member Functions
template<size_t Dim>
StripeIterator (const Index< Dim > &extents, size_t stripe_dim)
Construct from the grid points in each direction and which dimension the stripes are in.
StripeIterator ()=delete
Needed for Charm++ serialization.
operator bool () const noexcept
Returns true if the iterator is valid.
StripeIterator & operator++ ()
Increment to the next stripe.
size_t offset () const noexcept
Offset into DataVector for first element of stripe.
size_t stride () const noexcept
Stride of elements in DataVector for the stripe.
Detailed Description
Iterates over the 1-dimensional stripes with info on how to iterate over the current stripe.
Constructor & Destructor Documentation
StripeIterator() [1/2]
template<size_t Dim> StripeIterator::StripeIterator (const Index< Dim > & extents, size_t stripe_dim)
Construct from the grid points in each direction and which dimension the stripes are in.
StripeIterator() [2/2]
StripeIterator::StripeIterator () delete
Needed for Charm++ serialization.
Referenced by operator++().
Member Function Documentation
offset()
size_t StripeIterator::offset () const inline noexcept
Offset into DataVector for first element of stripe.
operator bool()
StripeIterator::operator bool () const inline noexcept
Returns true if the iterator is valid.
operator++()
StripeIterator & StripeIterator::operator++ ()
Increment to the next stripe.
References StripeIterator(), and UNLIKELY.
stride()
size_t StripeIterator::stride () const inline noexcept
Stride of elements in DataVector for the stripe.
References std::numeric_limits::max().
The documentation for this class was generated from the following files:
src/DataStructures/StripeIterator.hpp
src/DataStructures/StripeIterator.cpp