SpECTRE: EmbeddingMaps::Identity< Dim > Class Template Reference
EmbeddingMaps::Identity< Dim > Class Template Reference
Identity map from \(\xi \rightarrow x\).
#include <Identity.hpp>
Public Member Functions
Identity ()=default
~Identity () override=default
Identity (const Identity &)=delete
Identity (Identity &&) noexcept=default
Identity & operator= (const Identity &)=delete
Identity & operator= (Identity &&)=default
Point< Dim, Frame::Grid > operator() (const Point< Dim, Frame::Logical > &xi) const override
Point< Dim, Frame::Logical > inverse (const Point< Dim, Frame::Grid > &x) const override
double jacobian (const Point< Dim, Frame::Logical > &, const size_t ud, const size_t ld) const override
double inv_jacobian (const Point< Dim, Frame::Logical > &, const size_t ud, const size_t ld) const override
std::unique_ptr< EmbeddingMap< Dim, Dim > > get_clone () const override
Return a copy of the concrete EmbeddingMap.
WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< Dim, Dim >), Identity)
Identity (CkMigrateMessage *)
void pup (PUP::er &p) override
Public Member Functions inherited from EmbeddingMap< Dim, Dim >
WRAPPED_PUPable_abstract (EmbeddingMap)
EmbeddingMap ()=default
EmbeddingMap (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
~EmbeddingMap () override=default
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
virtual Point< DimOfRange, Frame::Grid > operator() (const Point< DimOfDomain, Frame::Logical > &xi) const=0
Apply the mapping (i.e. compute \(x^i(\xi^I)\)).
virtual Point< DimOfDomain, Frame::Logical > inverse (const Point< DimOfRange, Frame::Grid > &x) const=0
Apply the inverse mapping (i.e. compute \(\xi^I(x^i)\)).
virtual double jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
virtual double inv_jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
(i.e. compute \(\frac{\partial \xi^{ud}}{\partial x^{ld}}\)).
Detailed Description
template<size_t Dim>
class EmbeddingMaps::Identity< Dim >
Identity map from \(\xi \rightarrow x\).
Constructor & Destructor Documentation
Identity() [1/4]
template<size_t Dim> EmbeddingMaps::Identity< Dim >::Identity () default
~Identity()
template<size_t Dim> EmbeddingMaps::Identity< Dim >::~Identity () override default
Identity() [2/4]
template<size_t Dim> EmbeddingMaps::Identity< Dim >::Identity (const Identity< Dim > &) delete
Identity() [3/4]
template<size_t Dim> EmbeddingMaps::Identity< Dim >::Identity (Identity< Dim > &&) default noexcept
Identity() [4/4]
template<size_t Dim> EmbeddingMaps::Identity< Dim >::Identity (CkMigrateMessage *) inline explicit
Member Function Documentation
get_clone()
template<size_t Dim> std::unique_ptr<EmbeddingMap<Dim, Dim> > EmbeddingMaps::Identity< Dim >::get_clone () const inline override virtual
Return a copy of the concrete EmbeddingMap.
Implements EmbeddingMap< Dim, Dim >.
References EmbeddingMaps::Identity< Dim >::WRAPPED_PUPable_decl_base_template().
inv_jacobian()
template<size_t Dim> double EmbeddingMaps::Identity< Dim >::inv_jacobian (const Point< Dim, Frame::Logical > & , const size_t ud, const size_t ld) const inline override
References ASSERT.
Referenced by test_identity().
inverse()
template<size_t Dim> Point<Dim, Frame::Logical> EmbeddingMaps::Identity< Dim >::inverse (const Point< Dim, Frame::Grid > & x) const inline override
Referenced by test_identity().
jacobian()
template<size_t Dim> double EmbeddingMaps::Identity< Dim >::jacobian (const Point< Dim, Frame::Logical > & , const size_t ud, const size_t ld) const inline override
References ASSERT.
Referenced by test_identity().
operator()()
template<size_t Dim> Point<Dim, Frame::Grid> EmbeddingMaps::Identity< Dim >::operator() (const Point< Dim, Frame::Logical > & xi) const inline override
operator=() [1/2]
template<size_t Dim> Identity& EmbeddingMaps::Identity< Dim >::operator= (const Identity< Dim > &) delete
operator=() [2/2]
template<size_t Dim> Identity& EmbeddingMaps::Identity< Dim >::operator= (Identity< Dim > &&) default
pup()
template<size_t Dim> void EmbeddingMaps::Identity< Dim >::pup (PUP::er & p) inline override
WRAPPED_PUPable_decl_base_template()
template<size_t Dim> EmbeddingMaps::Identity< Dim >::WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< Dim, Dim >) , Identity< Dim >)
Referenced by EmbeddingMaps::Identity< Dim >::get_clone().
The documentation for this class was generated from the following file:
src/Domain/EmbeddingMaps/Identity.hpp