SpECTRE: Direction< VolumeDim > Class Template Reference
Direction< VolumeDim > Class Template Reference
Computational Domain
A particular Side along a particular coordinate Axis.
#include <Direction.hpp>
Public Member Functions
Direction (Axis axis, Side side)
Construct by specifying an Axis and a Side.
Direction (size_t dimension, Side side)
Construct by specifying a dimension and a Side.
Direction ()=default
Default constructor for Charm++ serialization.
size_t dimension () const noexcept
The dimension of the Direction.
Axis axis () const noexcept
The Axis of the Direction.
Side side () const noexcept
The side of the Direction.
double sign () const noexcept
The sign for the normal to the Side.
Direction< VolumeDim > opposite () const
The opposite Direction.
void pup (PUP::er &p)
Serialization for Charm++.
template<>
Direction (const size_t dimension, const Side side)
template<>
Direction (const size_t dimension, const Side side)
template<>
Direction (const size_t dimension, const Side side)
Static Public Member Functions
static Direction< VolumeDim > lower_xi ()
Helper functions for creating specific Directions. These are labeled by the logical-coordinate names (Xi,Eta,Zeta).
static Direction< VolumeDim > upper_xi ()
static Direction< VolumeDim > lower_eta ()
static Direction< VolumeDim > upper_eta ()
static Direction< VolumeDim > lower_zeta ()
static Direction< VolumeDim > upper_zeta ()
Detailed Description
template<size_t VolumeDim>
class Direction< VolumeDim >
A particular Side along a particular coordinate Axis.
Constructor & Destructor Documentation
Direction() [1/6]
template<size_t VolumeDim> Direction< VolumeDim >::Direction (Axis axis, Side side) inline
Construct by specifying an Axis and a Side.
References Direction< VolumeDim >::dimension(), Direction< VolumeDim >::Direction(), and Direction< VolumeDim >::side().
Direction() [2/6]
template<size_t VolumeDim> Direction< VolumeDim >::Direction (size_t dimension, Side side)
Construct by specifying a dimension and a Side.
Direction() [3/6]
template<size_t VolumeDim> Direction< VolumeDim >::Direction () default
Default constructor for Charm++ serialization.
Referenced by Direction< VolumeDim >::Direction(), Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
Direction() [4/6]
template<> Direction< 1 >::Direction (const size_t dimension, const Side side)
References ASSERT.
Direction() [5/6]
template<> Direction< 2 >::Direction (const size_t dimension, const Side side)
References ASSERT.
Direction() [6/6]
template<> Direction< 3 >::Direction (const size_t dimension, const Side side)
References ASSERT.
Member Function Documentation
axis()
template<size_t VolumeDim> Axis Direction< VolumeDim >::axis () const inline noexcept
The Axis of the Direction.
dimension()
template<size_t VolumeDim> size_t Direction< VolumeDim >::dimension () const inline noexcept
The dimension of the Direction.
Referenced by Direction< VolumeDim >::Direction(), operator!=(), operator<<(), and operator==().
lower_eta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::lower_eta () inline static
References Direction< VolumeDim >::Direction(), and Lower.
Referenced by Direction< VolumeDim >::sign().
lower_xi()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::lower_xi () inline static
Helper functions for creating specific Directions. These are labeled by the logical-coordinate names (Xi,Eta,Zeta).
References Direction< VolumeDim >::Direction(), and Lower.
Referenced by Direction< VolumeDim >::sign().
lower_zeta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::lower_zeta () inline static
References Direction< VolumeDim >::Direction(), and Lower.
Referenced by Direction< VolumeDim >::sign().
opposite()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::opposite () const inline
The opposite Direction.
Referenced by Direction< VolumeDim >::sign().
pup()
template<size_t VolumeDim> void Direction< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by Direction< VolumeDim >::sign().
side()
template<size_t VolumeDim> Side Direction< VolumeDim >::side () const inline noexcept
The side of the Direction.
Referenced by Direction< VolumeDim >::Direction().
sign()
template<size_t VolumeDim> double Direction< VolumeDim >::sign () const inline noexcept
The sign for the normal to the Side.
References Lower, Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), operator<<(), Direction< VolumeDim >::opposite(), Direction< VolumeDim >::pup(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
Referenced by operator!=(), operator<<(), and operator==().
upper_eta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::upper_eta () inline static
References Direction< VolumeDim >::Direction(), and Upper.
Referenced by Direction< VolumeDim >::sign().
upper_xi()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::upper_xi () inline static
References Direction< VolumeDim >::Direction(), and Upper.
Referenced by Direction< VolumeDim >::sign().
upper_zeta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::upper_zeta () inline static
References Direction< VolumeDim >::Direction(), and Upper.
Referenced by Direction< VolumeDim >::sign().
The documentation for this class was generated from the following file:
src/Domain/Direction.hpp