SpECTRE: db::DataBox< TagsLs< Tags... > > Class Template Reference
db::DataBox< TagsLs< Tags... > > Class Template Reference
DataBox
A DataBox stores objects that can be retrieved by using Tags.
#include <DataBox.hpp>
Public Types
using tags_list = typelist< Tags... >
A typelist of Tags that the DataBox holds.
Public Member Functions
template<typename T >
constexpr const item_type< T > & get () const noexcept
template<typename T >
constexpr item_type< T > & mutate () noexcept
Detailed Description
template<template< typename... > class TagsLs, typename... Tags>
class db::DataBox< TagsLs< Tags... > >
A DataBox stores objects that can be retrieved by using Tags.
Warning
The order of the tags in DataBoxes returned by create and create_from depends on implementation-defined behavior, and therefore should not be specified in source files. If explicitly naming a DataBox type is necessary they should be generated using get_databox_list.
Template Parameters
TagsLs a metasequence
Tags list of DataBoxTag's
Member Typedef Documentation
tags_list
template<template< typename... > class TagsLs, typename... Tags> using db::DataBox< TagsLs< Tags... > >::tags_list = typelist<Tags...>
A typelist of Tags that the DataBox holds.
Member Function Documentation
get()
template<template< typename... > class TagsLs, typename... Tags> template<typename T > constexpr const item_type<T>& db::DataBox< TagsLs< Tags... > >::get () const inline noexcept
Requires: Type T is one of the Tags corresponding to an object stored in the DataBox
Returns: The object corresponding to the Tag T
mutate()
template<template< typename... > class TagsLs, typename... Tags> template<typename T > constexpr item_type<T>& db::DataBox< TagsLs< Tags... > >::mutate () inline noexcept
Requires: Type T is one of the Tags corresponding to an object stored in the DataBox
mutate() is similar to get, however it allows altering the value of the item in the DataBox.
Returns: The object corresponding to the Tag T
References db::apply(), ASSERT, db::create(), db::create_from(), make_deferred(), and SPECTRE_ALWAYS_INLINE.
The documentation for this class was generated from the following file:
src/DataStructures/DataBox.hpp