SpECTRE: Matrix Class Reference
Matrix Class Reference
Data Structures
A dynamically sized matrix.
#include <Matrix.hpp>
Public Member Functions
Matrix (size_t number_of_rows, size_t number_of_colums, double value=std::numeric_limits< double >::signaling_NaN())
Create and set each element to value.
Matrix ()=default
Default constructor needed for serialization.
double & operator() (size_t i, size_t j) noexcept
const double & operator() (size_t i, size_t j) const noexcept
double * data () noexcept
const double * data () const noexcept
decltype(auto) begin ()
decltype(auto) begin () const
decltype(auto) end ()
decltype(auto) end () const
size_t rows () const noexcept
size_t columns () const noexcept
void pup (PUP::er &p)
Charm++ serialization.
Detailed Description
A dynamically sized matrix.
Constructor & Destructor Documentation
Matrix() [1/2]
Matrix::Matrix (size_t number_of_rows, size_t number_of_colums, double value = std::numeric_limits<double>::signaling_NaN())
Create and set each element to value.
Matrix() [2/2]
Matrix::Matrix () default
Default constructor needed for serialization.
Member Function Documentation
begin() [1/2]
decltype(auto) Matrix::begin () inline
Referenced by operator==().
begin() [2/2]
decltype(auto) Matrix::begin () const inline
columns()
size_t Matrix::columns () const inline noexcept
Referenced by operator<<(), and operator==().
data() [1/2]
double* Matrix::data () inline noexcept
Referenced by Basis::lgl::linear_filter_matrix().
data() [2/2]
const double* Matrix::data () const inline noexcept
end() [1/2]
decltype(auto) Matrix::end () inline
Referenced by operator==().
end() [2/2]
decltype(auto) Matrix::end () const inline
operator()() [1/2]
double& Matrix::operator() (size_t i, size_t j) inline noexcept
operator()() [2/2]
const double& Matrix::operator() (size_t i, size_t j) const inline noexcept
pup()
void Matrix::pup (PUP::er & p)
Charm++ serialization.
rows()
size_t Matrix::rows () const inline noexcept
Referenced by operator<<(), and operator==().
The documentation for this class was generated from the following files:
src/DataStructures/Matrix.hpp
src/DataStructures/Matrix.cpp