SpECTRE: SegmentId Class Reference
SegmentId Class Reference
Computational Domain
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
#include <SegmentId.hpp>
Public Member Functions
SegmentId ()=default
Default constructor needed for Charm++ serialization.
SegmentId (size_t refinement_level, size_t index)
size_t refinement_level () const noexcept
size_t index () const noexcept
SegmentId id_of_parent () const
SegmentId id_of_child (Side side) const
SegmentId id_if_flipped () const
The id this segment would have if the coordinate axis were flipped.
double endpoint (Side side) const
The logical coordinate of the endpoint of the segment on the given Side.
double midpoint () const
The logical coordinate of the midpoint of the segment.
void pup (PUP::er &p)
Serialization for Charm++.
Detailed Description
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
Constructor & Destructor Documentation
SegmentId() [1/2]
SegmentId::SegmentId () default
Default constructor needed for Charm++ serialization.
Referenced by id_if_flipped(), id_of_child(), and id_of_parent().
SegmentId() [2/2]
SegmentId::SegmentId (size_t refinement_level, size_t index)
References ASSERT, and two_to_the().
Member Function Documentation
endpoint()
double SegmentId::endpoint (Side side) const inline
The logical coordinate of the endpoint of the segment on the given Side.
References hash_value(), Lower, and two_to_the().
Referenced by index().
id_if_flipped()
SegmentId SegmentId::id_if_flipped () const inline
The id this segment would have if the coordinate axis were flipped.
References SegmentId(), and two_to_the().
Referenced by index().
id_of_child()
SegmentId SegmentId::id_of_child (Side side) const inline
References Lower, and SegmentId().
Referenced by index().
id_of_parent()
SegmentId SegmentId::id_of_parent () const inline
References ASSERT, and SegmentId().
Referenced by index().
index()
size_t SegmentId::index () const inline noexcept
References endpoint(), id_if_flipped(), id_of_child(), and id_of_parent().
Referenced by operator==().
midpoint()
double SegmentId::midpoint () const inline
The logical coordinate of the midpoint of the segment.
References std::numeric_limits::max(), operator!=(), operator<<(), operator==(), pup(), and two_to_the().
pup()
void SegmentId::pup (PUP::er & p)
Serialization for Charm++.
Referenced by midpoint().
refinement_level()
size_t SegmentId::refinement_level () const inline noexcept
Referenced by operator==().
The documentation for this class was generated from the following files:
src/Domain/SegmentId.hpp
src/Domain/SegmentId.cpp