SpECTRE: SliceIterator Class Reference
SliceIterator Class Reference
Data Structures
Iterate over a (dim-1)-dimensional slice.
#include <SliceIterator.hpp>
Public Member Functions
template<size_t Dim>
SliceIterator (const Index< Dim > &extents, size_t fixed_dim, size_t fixed_index)
SliceIterator ()=delete
Default constructor for serialization.
operator bool () const noexcept
Returns true if the iterator is valid.
SliceIterator & operator++ ()
Step to the next grid point.
size_t volume_offset () const noexcept
Offset into a Dim-dimensional Data at the current gridpoint. Note that the size of the Data is assumed to be that of the Mesh used to construct this SliceIterator.
size_t slice_offset () const noexcept
Offset into a (Dim-1)-dimensional Data at the current gridpoint. Note that the size of the Data is assumed to be that of a Mesh used to construct this SliceIterator with its fixedDim sliced away.
void reset ()
Reset the iterator.
Detailed Description
Iterate over a (dim-1)-dimensional slice.
Constructor & Destructor Documentation
SliceIterator() [1/2]
template<size_t Dim> SliceIterator::SliceIterator (const Index< Dim > & extents, size_t fixed_dim, size_t fixed_index)
Parameters
extents the number of grid points in each dimension
fixed_dim the dimension to slice in
fixed_index the index of the fixed_dim to slice at
SliceIterator() [2/2]
SliceIterator::SliceIterator () delete
Default constructor for serialization.
Referenced by reset().
Member Function Documentation
operator bool()
SliceIterator::operator bool () const inline noexcept
Returns true if the iterator is valid.
operator++()
SliceIterator & SliceIterator::operator++ ()
Step to the next grid point.
reset()
void SliceIterator::reset ()
Reset the iterator.
References SliceIterator().
slice_offset()
size_t SliceIterator::slice_offset () const inline noexcept
Offset into a (Dim-1)-dimensional Data at the current gridpoint. Note that the size of the Data is assumed to be that of a Mesh used to construct this SliceIterator with its fixedDim sliced away.
References std::numeric_limits::max().
volume_offset()
size_t SliceIterator::volume_offset () const inline noexcept
Offset into a Dim-dimensional Data at the current gridpoint. Note that the size of the Data is assumed to be that of the Mesh used to construct this SliceIterator.
The documentation for this class was generated from the following files:
src/DataStructures/SliceIterator.hpp
src/DataStructures/SliceIterator.cpp