SpECTRE: Index< Dim > Class Template Reference
Index< Dim > Class Template Reference
Data Structures
An integer multi-index.
#include <Index.hpp>
Public Member Functions
Index (const size_t i0=std::numeric_limits< size_t >::max())
Construct with each element set to the same value.
template<typename... I, std::enable_if_t<(sizeof...(I) > 1>
Index (I... i)
Construct specifying value in each dimension.
Index (std::array< size_t, Dim > i)
size_t operator[] (const size_t d) const noexcept
size_t & operator[] (const size_t d) noexcept
std::array< size_t, Dim >::iterator begin ()
std::array< size_t, Dim >::const_iterator begin () const
std::array< size_t, Dim >::iterator end ()
std::array< size_t, Dim >::const_iterator end () const
template<int N = Dim, std::enable_if_t<(N > 0>
constexpr size_t product () const noexcept
The product of the indices. If Dim = 0, the product is defined as 1.
template<size_t N = Dim, std::enable_if_t<(N > 0>
Index< Dim - 1 > slice_away (const size_t d) const
Return a smaller Index with the d-th elmenent removed.
const size_t * data () const noexcept
size_t * data () noexcept
Friends
template<size_t N>
std::ostream & operator<< (std::ostream &os, const Index< N > &i)
Detailed Description
template<size_t Dim>
class Index< Dim >
An integer multi-index.
Template Parameters
Dim the number of integers in the Index.
Constructor & Destructor Documentation
Index() [1/3]
template<size_t Dim> Index< Dim >::Index (const size_t i0 = std::numeric_limits<size_t>::max()) inline explicit
Construct with each element set to the same value.
Index() [2/3]
template<size_t Dim> template<typename... I, std::enable_if_t<(sizeof...(I) > 1> Index< Dim >::Index (I... i) inline explicit
Construct specifying value in each dimension.
References cpp17::conjunction_v.
Index() [3/3]
template<size_t Dim> Index< Dim >::Index (std::array< size_t, Dim > i) inline explicit
Member Function Documentation
begin() [1/2]
template<size_t Dim> std::array<size_t, Dim>::iterator Index< Dim >::begin () inline
begin() [2/2]
template<size_t Dim> std::array<size_t, Dim>::const_iterator Index< Dim >::begin () const inline
data() [1/2]
template<size_t Dim> const size_t* Index< Dim >::data () const inline noexcept
data() [2/2]
template<size_t Dim> size_t* Index< Dim >::data () inline noexcept
end() [1/2]
template<size_t Dim> std::array<size_t, Dim>::iterator Index< Dim >::end () inline
end() [2/2]
template<size_t Dim> std::array<size_t, Dim>::const_iterator Index< Dim >::end () const inline
operator[]() [1/2]
template<size_t Dim> size_t Index< Dim >::operator[] (const size_t d) const inline noexcept
References gsl::at().
operator[]() [2/2]
template<size_t Dim> size_t& Index< Dim >::operator[] (const size_t d) inline noexcept
References gsl::at().
product()
template<size_t Dim> template<int N = Dim, std::enable_if_t<(N > 0> constexpr size_t Index< Dim >::product () const inline noexcept
The product of the indices. If Dim = 0, the product is defined as 1.
slice_away()
template<size_t Dim> template<size_t N = Dim, std::enable_if_t<(N > 0> Index<Dim - 1> Index< Dim >::slice_away (const size_t d) const inline
Return a smaller Index with the d-th elmenent removed.
Parameters
d the element to remove.
References gsl::at().
Friends And Related Function Documentation
operator<<
template<size_t Dim> template<size_t N> std::ostream& operator<< (std::ostream & os, const Index< N > & i) friend
The documentation for this class was generated from the following file:
src/DataStructures/Index.hpp