SpECTRE: src/Domain/Direction.cpp File Reference
Direction.cpp File Reference
#include "Domain/Direction.hpp"
#include <ostream>
#include "ErrorHandling/Assert.hpp"
Functions
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &os, const Direction< VolumeDim > &direction)
Output operator for a Direction.
template std::ostream & operator<< (std::ostream &, const Direction< 1 > &)
template std::ostream & operator<< (std::ostream &, const Direction< 2 > &)
template std::ostream & operator<< (std::ostream &, const Direction< 3 > &)
Function Documentation
operator<<() [1/4]
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & os, const Direction< VolumeDim > & direction)
Output operator for a Direction.
References Direction< VolumeDim >::dimension(), and Direction< VolumeDim >::sign().
Referenced by Direction< VolumeDim >::sign().
operator<<() [2/4]
template std::ostream& operator<< (std::ostream & , const Direction< 1 > &)
operator<<() [3/4]
template std::ostream& operator<< (std::ostream & , const Direction< 2 > &)
operator<<() [4/4]
template std::ostream& operator<< (std::ostream & , const Direction< 3 > &)