SpECTRE: src/Domain/Direction.hpp File Reference
Direction.hpp File Reference
Defines class template Direction.
#include <functional>
#include <iosfwd>
#include <pup.h>
#include "Domain/Side.hpp"
#include "Parallel/PupStlCpp11.hpp"
Classes
class Direction< VolumeDim >
A particular Side along a particular coordinate Axis.
Enumerations
enum Axis
enum Axis
enum Axis
Functions
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &os, const Direction< VolumeDim > &direction)
Output operator for a Direction.
template<size_t VolumeDim>
bool operator== (const Direction< VolumeDim > &lhs, const Direction< VolumeDim > &rhs)
template<size_t VolumeDim>
bool operator!= (const Direction< VolumeDim > &lhs, const Direction< VolumeDim > &rhs)
Detailed Description
Defines class template Direction.
Enumeration Type Documentation
Axis [1/3]
enum Axis strong
Axis [2/3]
enum Axis strong
Axis [3/3]
enum Axis strong
Function Documentation
operator!=()
template<size_t VolumeDim> bool operator!= (const Direction< VolumeDim > & lhs, const Direction< VolumeDim > & rhs) inline
References Direction< VolumeDim >::dimension(), and Direction< VolumeDim >::sign().
operator<<()
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & os, const Direction< VolumeDim > & direction)
Output operator for a Direction.
References Direction< VolumeDim >::dimension(), and Direction< VolumeDim >::sign().
Referenced by Direction< VolumeDim >::sign().
operator==()
template<size_t VolumeDim> bool operator== (const Direction< VolumeDim > & lhs, const Direction< VolumeDim > & rhs) inline
References Direction< VolumeDim >::dimension(), and Direction< VolumeDim >::sign().