SpECTRE: DataBox
DataBox
Contains (meta)functions used for manipulating DataBoxes.
Namespaces
db
Namespace for DataBox related things.
Classes
class db::DataBox< TagsLs< Tags... > >
A DataBox stores objects that can be retrieved by using Tags.
struct db::DataBoxTag
Tags for the DataBox inherit from this type.
struct db::DataBoxPrefix
Marks an item as being a prefix to another tag.
struct db::ComputeItemTag
Marks a DataBoxTag as being a compute item that executes a function.
struct db::is_compute_item< T, typename >
Check if T derives off of db::ComputeItemTag.
struct db::is_simple_compute_item< T, typename >
Check if a Compute Item is "simple".
struct db::is_variables_compute_item< T, typename >
Check if a Compute Item returns a Variables class.
Typedefs
template<typename Ls >
using db::get_databox_list = tmpl::sort< Ls, db::detail::databox_tag_less< tmpl::_1, tmpl::_2 > >
Compute the canonical typelist used in the DataBox.
template<typename... Tags>
using db::RemoveTags = tmpl::flatten< typelist< Tags... > >
List of Tags to remove from the DataBox.
template<typename... Tags>
using db::AddTags = tmpl::flatten< typelist< Tags... > >
List of Tags to add to the DataBox.
template<typename... Tags>
using db::AddComputeItemsTags = tmpl::flatten< typelist< Tags... > >
List of Compute Item Tags to add to the DataBox.
template<typename DataBoxTagsLs , typename KeepTagsLs >
using db::remove_tags_from_keep_tags = tmpl::filter< DataBoxTagsLs, detail::filter_helper< tmpl::pin< KeepTagsLs >, tmpl::_1 > >
Get typelist of tags to remove from a DataBox so as to keep only desired tags.
using db::DataBoxString_t = const char *const
The string used to give a runtime name to a DataBoxTag.
template<typename T >
using db::item_type = typename detail::compute_item_result_impl< T >::type
Get the type that is returned by a Compute Item.
Functions
template<typename AddTags , typename AddComputeItems = typelist<>, typename... Args>
constexpr auto db::create (Args &&... args)
Create a new DataBox.
template<typename RemoveTags , typename AddTags = typelist<>, typename AddComputeItems = typelist<>, typename Box , typename... Args>
constexpr auto db::create_from (const Box &box, Args &&... args)
Create a new DataBox from an existing one adding or removing items and compute items.
template<typename Type , typename TagLs >
constexpr const Type & db::get_item_from_box (const DataBox< TagLs > &box, const std::string &tag_name)
Retrieve an item from the DataBox that has a tag with label tag_name and type Type
template<typename TagsLs , typename F , typename... BoxTags, typename... Args>
constexpr auto db::apply (F f, const DataBox< BoxTags... > &box, Args &&... args)
Apply the function f with argument Tags TagLs from DataBox box
template<typename TagsLs , typename F , typename... BoxTags, typename... Args>
constexpr auto db::apply_with_box (F f, const DataBox< BoxTags... > &box, Args &&... args)
Apply the function f with argument Tags TagLs from DataBox box and box as the first argument.
Variables
template<typename T >
constexpr bool db::is_compute_item_v = is_compute_item<T>::value
Check if T derives off of db::ComputeItemTag.
template<typename Tag , std::enable_if_t< not std::is_base_of< DataBoxPrefix, Tag >::value > * = nullptr>
std::string db::get_tag_name ()
Get the name of a DataBoxTag, including prefixes.
Detailed Description
Contains (meta)functions used for manipulating DataBoxes.
Typedef Documentation
AddComputeItemsTags
template<typename... Tags> using db::AddComputeItemsTags = typedef tmpl::flatten<typelist<Tags...> >
List of Compute Item Tags to add to the DataBox.
AddTags
template<typename... Tags> using db::AddTags = typedef tmpl::flatten<typelist<Tags...> >
List of Tags to add to the DataBox.
DataBoxString_t
using db::DataBoxString_t = typedef const char* const
The string used to give a runtime name to a DataBoxTag.
get_databox_list
template<typename Ls > using db::get_databox_list = typedef tmpl::sort<Ls, db::detail::databox_tag_less<tmpl::_1, tmpl::_2> >
Compute the canonical typelist used in the DataBox.
Note
The result is architecture-dependent.
Requires: tt::is_a<typelist, Ls>::value is true
Returns: typelist of all elements in Ls but ordered for the db::DataBox
item_type
template<typename T > using db::item_type = typedef typename detail::compute_item_result_impl<T>::type
Get the type that is returned by a Compute Item.
remove_tags_from_keep_tags
template<typename DataBoxTagsLs , typename KeepTagsLs > using db::remove_tags_from_keep_tags = typedef tmpl::filter<DataBoxTagsLs, detail::filter_helper<tmpl::pin<KeepTagsLs>, tmpl::_1> >
Get typelist of tags to remove from a DataBox so as to keep only desired tags.
Returns: a typelist of tags that need to be removed from the DataBox with tags DataBoxTagsLs in order to keep the tags in KeepTagsLs
Example
using full_list = tmpl::list<double, char, int, bool, X<int>>;
using keep_list = tmpl::list<double, bool>;
static_assert(
    std::is_same<typelist<char, int, X<int>>,
                 db::remove_tags_from_keep_tags<full_list, keep_list>>::value,
    "Failed testing db::remove_tags_from_keep_tags");
using keep_list2 = tmpl::list<double, bool, X<int>>;
static_assert(
    std::is_same<typelist<char, int>,
                 db::remove_tags_from_keep_tags<full_list, keep_list2>>::value,
    "Failed testing db::remove_tags_from_keep_tags");
RemoveTags
template<typename... Tags> using db::RemoveTags = typedef tmpl::flatten<typelist<Tags...> >
List of Tags to remove from the DataBox.
Function Documentation
apply()
template<typename TagsLs , typename F , typename... BoxTags, typename... Args> constexpr auto db::apply (F f, const DataBox< BoxTags... > & box, Args &&... args) inline
Apply the function f with argument Tags TagLs from DataBox box
Details
Apply the function f with arguments that are of type Tags::type where Tags is defined as TagLs<Tags...>. The arguments to f are retrieved from the DataBox box.
Usage
Given a function func that takes arguments of types T1, T2, A1 and A2. Let the Tags for the quantities of types T1 and T2 in the DataBox box be Tag1 and Tag2, and objects a1 of type A1 and a2 of type A2, then
auto result = apply<typelist<Tag1, Tag2>>(func, box, a1, a2);
Returns: decltype(func(box.get<Tag1>(), box.get<Tag2>(), a1, a2))
Semantics: For tags Tags... in a DataBox box, and a function func that takes sizeof...(Tags) arguments of types typename Tags::type..., and sizeof...(Args) arguments of types Args...,
result = func(box, box.get<Tags>()..., args...);
Example
  auto check_result_args = [](const std::string& sample_string,
                              const auto& computed_string, const auto& vector) {
    CHECK(sample_string == "My Sample String"s);
    CHECK(computed_string == "My Sample String6.28"s);
    CHECK(vector == (std::vector<double>{8.7, 93.2, 84.7}));
  };
  db::apply<typelist<test_databox_tags::Tag2, test_databox_tags::ComputeTag1>>(
      check_result_args, original_box,
      original_box.get<test_databox_tags::Tag1>());
See also
apply_with_box DataBox
Template Parameters
TagsLs typelist of Tags in the order that they are to be passed to f
Parameters
f the function to apply
box the DataBox out of which to retrieve the Tags and to pass to f
args the arguments to pass to the function that are not in the DataBox, box
Referenced by TensorExpressions::contract(), cube(), DataVector::erfc(), TensorExpressions::TensorContract< Index1, Index2, T, X, Symm, IndexLs, ArgsLs >::get(), TensorExpression< Derived, DataType, Symm, IndexLs, ArgsLs< Args... > >::get(), db::get_item_from_box(), db::DataBox< TagsLs< Tags... > >::mutate(), Tensor< X, Symm, IndexLs< Indices... > >::operator()(), TensorExpression< Derived, DataType, Symm, IndexLs, ArgsLs< Args... > >::operator~(), and pow().
apply_with_box()
template<typename TagsLs , typename F , typename... BoxTags, typename... Args> constexpr auto db::apply_with_box (F f, const DataBox< BoxTags... > & box, Args &&... args) inline
Apply the function f with argument Tags TagLs from DataBox box and box as the first argument.
Details
Apply the function f with arguments that are of type Tags::type where Tags is defined as TagLs<Tags...>. The arguments to f are retrieved from the DataBox box and the first argument passed to f is the DataBox.
Usage
Given a function func that takes arguments of types DataBox<Tags...>, T1, T2, A1 and A2. Let the Tags for the quantities of types T1 and T2 in the DataBox box be Tag1 and Tag2, and objects a1 of type A1 and a2 of type A2, then
auto result = apply_with_box<typelist<Tag1, Tag2>>(func, box, a1, a2);
Returns: decltype(func(box, box.get<Tag1>(), box.get<Tag2>(), a1, a2))
Semantics: For tags Tags... in a DataBox box, and a function func that takes as its first argument a value of typedecltype(box), sizeof...(Tags) arguments of types typename Tags::type..., and sizeof...(Args) arguments of types Args...,
result = func(box, box.get<Tags>()..., args...);
Example
  auto check_result_args = [](const auto& box, const std::string& sample_string,
                              const std::string& computed_string,
                              const std::vector<int>& vector) {
    CHECK(sample_string == "My Sample String"s);
    CHECK(computed_string == "My Sample String6.28"s);
    CHECK(box.template get<test_databox_tags::Tag1>() ==
          (std::vector<double>{8.7, 93.2, 84.7}));
    CHECK((vector == std::vector<int>{1, 4, 8}));
  };
  db::apply_with_box<
      typelist<test_databox_tags::Tag2, test_databox_tags::ComputeTag1>>(
      check_result_args, original_box, std::vector<int>{1, 4, 8});
See also
apply DataBox
Template Parameters
TagsLs typelist of Tags in the order that they are to be passed to f
Parameters
f the function to apply
box the DataBox out of which to retrieve the Tags and to pass to f
args the arguments to pass to the function that are not in the DataBox, box
Referenced by db::get_item_from_box().
create()
template<typename AddTags , typename AddComputeItems = typelist<>, typename... Args> constexpr auto db::create (Args &&... args)
Create a new DataBox.
Details
Creates a new DataBox holding types Tags::type filled with the arguments passed to the function. Compute items must be added so that the dependencies of a compute item are added before the compute item. For example, say you have compute items A and B where B depends on A, then you must add them using db::AddComputeItemsTags<A, B>.
Example
  auto original_box =
      db::create<db::AddTags<test_databox_tags::Tag0, test_databox_tags::Tag1,
                             test_databox_tags::Tag2>,
                 db::AddComputeItemsTags<test_databox_tags::ComputeTag0,
                                         test_databox_tags::ComputeTag1,
                                         test_databox_tags::ComputeLambda0,
                                         test_databox_tags::ComputeLambda1>>(
          3.14, std::vector<double>{8.7, 93.2, 84.7}, "My Sample String"s);
See also
create_from get_tags_from_box
Template Parameters
AddTags the tags of the args being added
AddComputeItems list of compute item tags to add to the DataBox
Parameters
args the data to be added to the DataBox
Referenced by db::DataBox< TagsLs< Tags... > >::mutate().
create_from()
template<typename RemoveTags , typename AddTags = typelist<>, typename AddComputeItems = typelist<>, typename Box , typename... Args> constexpr auto db::create_from (const Box & box, Args &&... args)
Create a new DataBox from an existing one adding or removing items and compute items.
Example
Removing an item or compute item is done using:
    auto box =
        db::create_from<db::RemoveTags<test_databox_tags::Tag1>>(original_box);
Adding an item is done using:
    auto box =
        db::create_from<db::RemoveTags<>, db::AddTags<test_databox_tags::Tag3>>(
            original_box, "Yet another test string"s);
Adding a compute item is done using:
    auto box =
        db::create_from<db::RemoveTags<>, db::AddTags<test_databox_tags::Tag3>>(
            original_box, "Yet another test string"s);
See also
create DataBox get_tags_from_box
Template Parameters
RemoveTags typelist of Tags to remove
AddTags typelist of Tags corresponding to the arguments to be added
AddComputeItems list of compute item tags to add to the DataBox
Parameters
box the DataBox the new box should be based off
args the values for the items to add to the DataBox
Returns: DataBox like box but altered by RemoveTags and AddTags
References ERROR, and db::get_item_from_box().
Referenced by db::DataBox< TagsLs< Tags... > >::mutate().
get_item_from_box()
template<typename Type , typename TagLs > constexpr const Type& db::get_item_from_box (const DataBox< TagLs > & box, const std::string & tag_name)
Retrieve an item from the DataBox that has a tag with label tag_name and type Type
Details
The type that the tag represents must be of the type Type, and the tag must have the label tag_name. The function iterates over all tags in the DataBox box that have the type Type searching linearly for one whose label matches tag_name.
Example
  auto original_box = db::create<
      db::AddTags<test_databox_tags::Tag0, test_databox_tags::Tag1,
                  test_databox_tags::Tag2,
                  test_databox_tags::TagPrefix<test_databox_tags::Tag0>>,
      db::AddComputeItemsTags<test_databox_tags::ComputeTag0,
                              test_databox_tags::ComputeTag1>>(
      3.14, std::vector<double>{8.7, 93.2, 84.7}, "My Sample String"s, 8.7);
  const std::string compute_string =
      db::get_item_from_box<std::string>(original_box, "ComputeTag1");
Template Parameters
Type the type of the tag with the label tag_name
Parameters
box the DataBox through which to search
tag_name the label of the tag to retrieve
References db::apply(), and db::apply_with_box().
Referenced by db::create_from().
get_tag_name()
template<typename Tag , std::enable_if_t< not std::is_base_of< DataBoxPrefix, Tag >::value > * = nullptr> std::string db::get_tag_name ()
Get the name of a DataBoxTag, including prefixes.
Details
Given a DataBoxTag returns the name of the DataBoxTag as a std::string. If the DataBoxTag is also a DataBoxPrefix then the prefix is added.
Template Parameters
Tag the DataBoxTag whose name to get
Returns: string holding the DataBoxTag's name
References cstring_hash().
Variable Documentation
is_compute_item_v
template<typename T > constexpr bool db::is_compute_item_v = is_compute_item<T>::value
Check if T derives off of db::ComputeItemTag.