SpECTRE: Error Handling
Error Handling
Macros
#define ASSERT(a, m)
Assert that an expression should be true.
#define CASSERT(a, m)
Assert that an expression should be true.
#define ERROR(m)
prints an error message to the standard error stream and aborts the program.
#define CERROR(m)
prints an error message to the standard error and aborts the program.
Functions
void abort_with_error_message (const char *expression, const char *file, int line, const std::string &message)
Compose an error message with an expression and abort the program.
void abort_with_error_message (const char *file, int line, const std::string &message)
Compose an error message and abort the program.
void enable_floating_point_exceptions ()
After a call to this function, the code will terminate with a floating point exception on overflow, divide-by-zero, and invalid operations.
void disable_floating_point_exceptions ()
After a call to this function, the code will NOT terminate with a floating point exception on overflow, divide-by-zero, and invalid operations.
Detailed Description
Macros and functions used for handling errors
Macro Definition Documentation
ASSERT
#define ASSERT (a, m)
Value:
do {                                                 \
    if (false) {                                       \
      static_cast<void>(a);                            \
      std::ostringstream avoid_name_collisions_ASSERT; \
      avoid_name_collisions_ASSERT << m;               \
      static_cast<void>(avoid_name_collisions_ASSERT); \
    }                                                  \
  } while (false)
Assert that an expression should be true.
If the preprocessor macro SPECTRE_DEBUG is defined and the expression is false, an error message is printed to the standard error stream, and the program aborts. ASSERT should be used to catch coding errors as it does nothing in production code.
Parameters
a the expression that must be true
m the error message as an ostream
CASSERT
#define CASSERT (a, m)
Assert that an expression should be true.
Just like ASSERT and so the same guidelines apply. However, because it does not use std::stringstream it can be used in some constexpr functions where ASSERT cannot be.
Parameters
a the expression that must be satisfied
m a std::string holding the error message
CERROR
#define CERROR (m)
Value:
do {                                                                     \
    Parallel::abort("\n################ ERROR ################\nLine: "s + \
                    std::to_string(__LINE__) + " of file '"s + __FILE__ +  \
                    "'\n"s + m + /* NOLINT */                              \
                    "\n#######################################\n"s);       \
  } while (false)
prints an error message to the standard error and aborts the program.
CERROR is just like ERROR and so the same guidelines apply. However, because it does not use std::stringstream it can be used in some constexpr functions where ERROR cannot be.
Parameters
m error message as a string, may need to use string literals
ERROR
#define ERROR (m)
Value:
do {                                                           \
    std::ostringstream avoid_name_collisions_ERROR;              \
    avoid_name_collisions_ERROR << m; /* NOLINT */               \
    abort_with_error_message(__FILE__, __LINE__,                 \
                             avoid_name_collisions_ERROR.str()); \
  } while (false)
prints an error message to the standard error stream and aborts the program.
ERROR should not be used for coding errors, but instead for user errors or failure modes of numerical algorithms. An acceptable use for error is also in the default case of a switch statement.
Parameters
m an arbitrary output stream.
Function Documentation
abort_with_error_message() [1/2]
void abort_with_error_message (const char * expression, const char * file, int line, const std::string & message)
Compose an error message with an expression and abort the program.
References Parallel::abort(), Parallel::my_node(), and Parallel::my_proc().
abort_with_error_message() [2/2]
void abort_with_error_message (const char * file, int line, const std::string & message)
Compose an error message and abort the program.
References Parallel::abort(), Parallel::my_node(), and Parallel::my_proc().
disable_floating_point_exceptions()
void disable_floating_point_exceptions ()
After a call to this function, the code will NOT terminate with a floating point exception on overflow, divide-by-zero, and invalid operations.
enable_floating_point_exceptions()
void enable_floating_point_exceptions ()
After a call to this function, the code will terminate with a floating point exception on overflow, divide-by-zero, and invalid operations.
Referenced by RunTests::RunTests().