SpECTRE: Utilities
Utilities
A collection of useful classes, functions and metafunctions.
Namespaces
gsl
Implementations from the Guideline Support Library.
Classes
class Deferred< Rt >
Provides deferred or lazy evaluation of a function or function object, as well as efficient storage of an object that is mutable.
struct PointerVector< Type, AF, PF, TF >
A raw pointer endowed with expression template support via the Blaze library.
struct TaggedTuple< Tags >
An associative container that is indexed by structs.
struct TypeDisplayer<... >
Get compiler error with type of template parameter.
Macros
#define DEFINE_FAKE_VIRTUAL(function)
Define a function that acts similarly to a virtual function, but can take template parameters.
#define SPECTRE_ALWAYS_INLINE inline
Always inline a function. Only use this if you benchmarked the code.
#define LIKELY(x) (x)
#define UNLIKELY(x) (x)
Typedefs
template<typename Sequence >
using make_boost_variant_over = typename detail::make_boost_variant_over_impl< Sequence >::type
Create a boost::variant with all all the types inside the typelist Sequence.
template<typename... Ts>
using typelist = tmpl::list< Ts... >
Construct a typelist of types Ts.
Functions
std::string info_from_build ()
Information about the version, date, host, git commit, and link time.
std::string spectre_version ()
Retrieve a string containing the current version of SpECTRE.
int spectre_major_version ()
Returns major version.
int spectre_minor_version ()
Returns minor version.
int spectre_patch_version ()
Returns patch version.
double ddot_ (const size_t &N, const double *X, const size_t &INCX, const double *Y, const size_t &INCY)
template<typename Fp , typename... Args>
Deferred< Rt1 > make_deferred (Fp f, Args &&... args)
Create a deferred function call object.
template<class T , class U >
constexpr T gsl::narrow_cast (U &&u) noexcept
Cast u to a type T where the cast may result in narrowing.
template<class T , class U >
T gsl::narrow (U u)
A checked version of narrow_cast() that ERRORs if the cast changed the value.
constexpr size_t operator"" _st (const unsigned long long n)
Defines the _st size_t suffix.
template<std::size_t size, typename T >
constexpr std::array< std::decay_t< T >, size > make_array (T &&value)
Helper class to initialize a std::array.
template<typename T , typename... V, typename std::enable_if_t<(sizeof...(V) > 0>
constexpr std::array< typename std::decay_t< T >, sizeof...(V)+1 > make_array (T &&t, V &&... values)
Helper function to initialize a std::array with varying number of arguments.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::list< T > &v)
Output the items of a std::list.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< T > &v)
Output the items of a std::vector.
template<typename T , size_t N>
std::ostream & operator<< (std::ostream &os, const std::array< T, N > &a)
Output the items of a std::array.
template<typename... Args>
std::ostream & operator<< (std::ostream &os, const std::tuple< Args... > &t)
Stream operator for tuples.
template<typename Map , typename std::enable_if_t< tt::is_maplike< Map >::value > * >
std::ostream & operator<< (std::ostream &os, const Map &m)
Output all the key, value pairs of a map.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::unordered_set< T > &v)
Output the items of a std::unordered_set.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::set< T > &v)
Output the items of a std::unordered_set.
template<typename T , typename std::enable_if_t< tt::is_streamable< std::ostream, T >::value > * >
std::ostream & operator<< (std::ostream &os, const std::unique_ptr< T > &t)
Stream operator for std::unique_ptr.
template<typename T , typename std::enable_if_t< tt::is_streamable< std::ostream, T >::value > * >
std::ostream & operator<< (std::ostream &os, const std::shared_ptr< T > &t)
Stream operator for std::shared_ptr.
template<typename T , typename U >
std::ostream & operator<< (std::ostream &os, const std::pair< T, U > &t)
Stream operator for std::pair.
template<typename Map , typename std::enable_if_t< tt::is_maplike< Map >::value > * = nullptr>
std::string keys_of (const Map &m)
Construct a string containing the keys of a map.
template<typename... Args>
std::string formatted_string (const std::string &fmt, Args... args)
Format a string like printf.
template<bool UseLibXsmm = false>
void dgemm_ (const char &TRANSA, const char &TRANSB, const size_t &M, const size_t &N, const size_t &K, const double &ALPHA, const double *A, const size_t &LDA, const double *B, const size_t &LDB, const double &BETA, double *C, const size_t &LDC)
Perform a matrix-matrix multiplication.
template<>
void dgemm_< true > (const char &TRANSA, const char &TRANSB, const size_t &M, const size_t &N, const size_t &K, const double &ALPHA, const double *A, const size_t &LDA, const double *B, const size_t &LDB, const double &BETA, double *C, const size_t &LDC)
Perform a matrix-matrix multiplication.
void dgemv_ (const char &TRANS, const size_t &M, const size_t &N, const double &ALPHA, const double *A, const size_t &LDA, const double *X, const size_t &INCX, const double &BETA, double *Y, const size_t &INCY)
Perform a matrix-vector multiplication.
template<class T , std::size_t N, typename Size >
constexpr T & gsl::at (std::array< T, N > &arr, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<class Cont , typename Size >
constexpr const Cont::value_type & gsl::at (const Cont &cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<class T , typename Size >
constexpr const T & gsl::at (std::initializer_list< T > cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
Detailed Description
A collection of useful classes, functions and metafunctions.
Macro Definition Documentation
DEFINE_FAKE_VIRTUAL
#define DEFINE_FAKE_VIRTUAL (function)
Define a function that acts similarly to a virtual function, but can take template parameters.
Details
DEFINE_FAKE_VIRTUAL(func) defines the function fake_virtual_func and the struct FakeVirtualInherit_func. It should usually be called in a detail namespace.
A base class Base using this functionality should define a type
using Inherit = FakeVirtualInherit_func<Base>;
and a member function func wrapping fake_virtual_func, with the wrapper passing the derived classes as a typelist as the first template argument and the this pointer as the first normal argument.
Derived classes should then inherit from Base::Inherit instead of directly from Base. (Base::Inherit inherits from Base.)
If the base class has no pure virtual functions remaining it will generally be desirable to mark the constructors and assignment operators protected so that a bare base class cannot be instantiated.
If it is necessary to use multiple fake virtual functions with the same base class, the Inherit definition can nest the fake virtual classes:
using Inherit = FakeVirtualInherit_func1<FakeVirtualInherit_func2<Base>>;
Example
DEFINE_FAKE_VIRTUAL(fv)
class Derived;
class Base {
 public:
  using Inherit = FakeVirtualInherit_fv<Base>;
 protected:
  Base() = default;
  Base(const Base&) = default;
  Base(Base&&) = default;
  Base& operator=(const Base&) = default;
  Base& operator=(Base&&) = default;
 public:
  virtual ~Base() = default;
  template <typename T>
  int fv(int x) {
    return fake_virtual_fv<typelist<Derived>, T>(this, x);
  }
};
class Derived : public Base::Inherit {
 public:
  template <typename T>
  int fv(int x) {
    return x + 3;
  }
};
LIKELY
#define LIKELY (x) (x)
The if statement is expected to evaluate true most of the time
SPECTRE_ALWAYS_INLINE
#define SPECTRE_ALWAYS_INLINE inline
Always inline a function. Only use this if you benchmarked the code.
Referenced by TensorExpressions::AddSub< T1, T2, ArgsLs1< Args1... >, ArgsLs2< Args2... >, Sign >::AddSub(), TensorExpressions::contract(), cube(), DataVector::erfc(), TensorExpressions::TensorContract< Index1, Index2, T, X, Symm, IndexLs, ArgsLs >::fill_contracting_tensor_index(), TensorExpressions::AddSub< T1, T2, ArgsLs1< Args1... >, ArgsLs2< Args2... >, Sign >::get(), TensorExpression< Derived, DataType, Symm, IndexLs, ArgsLs< Args... > >::get(), Tensor< X, Symm, IndexLs< Indices... > >::get_tensor_index(), Tensor< X, Symm, IndexLs< Indices... > >::index_dim(), Tensor< X, Symm, IndexLs< Indices... > >::index_dims(), Tensor< X, Symm, IndexLs< Indices... > >::index_types(), Tensor< X, Symm, IndexLs< Indices... > >::index_valences(), make_array(), Variables< tmpl::list< Tags... > >::operator/(), TensorExpression< Derived, DataType, Symm, IndexLs, ArgsLs< Args... > >::operator~(), TensorExpressions::Product< T1, T2, ArgsLs1< Args1... >, ArgsLs2< Args2... > >::Product(), Tensor< X, Symm, IndexLs< Indices... > >::rank(), and Tensor< X, Symm, IndexLs< Indices... > >::symmetries().
UNLIKELY
#define UNLIKELY (x) (x)
The if statement is expected to evaluate false most of the time
Referenced by StripeIterator::operator++(), and IndexIterator< Dim >::operator++().
Typedef Documentation
make_boost_variant_over
template<typename Sequence > using make_boost_variant_over = typename detail::make_boost_variant_over_impl<Sequence>::type
Create a boost::variant with all all the types inside the typelist Sequence.
Returns: boost::variant of all types inside Sequence
typelist
template<typename... Ts> using typelist = tmpl::list<Ts...>
Construct a typelist of types Ts.
Function Documentation
at() [1/3]
template<class T , std::size_t N, typename Size > constexpr T& gsl::at (std::array< T, N > & arr, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
References Expects.
Referenced by Tensor< X, Symm, IndexLs< Indices... > >::get(), Tensor< X, Symm, IndexLs< Indices... > >::index_dim(), make_array_from_list(), Index< Dim >::operator[](), Tensor< X, Symm, IndexLs< Indices... > >::operator[](), and Index< Dim >::slice_away().
at() [2/3]
template<class Cont , typename Size > constexpr const Cont::value_type& gsl::at (const Cont & cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
References Expects.
at() [3/3]
template<class T , typename Size > constexpr const T& gsl::at (std::initializer_list< T > cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
References Expects.
ddot_()
double ddot_ (const size_t & N, const double * X, const size_t & INCX, const double * Y, const size_t & INCY) inline
The dot product of two vectors.
Parameters
N the length of the vectors.
X a pointer to the first element of the first vector.
INCX the stride for the elements of the first vector.
Y a pointer to the first element of the second vector.
INCY the stride for the elements of the second vector.
Returns: the dot product of the given vectors.
Referenced by Basis::lgl::definite_integral< 1 >().
dgemm_()
template<bool UseLibXsmm = false> void dgemm_ (const char & TRANSA, const char & TRANSB, const size_t & M, const size_t & N, const size_t & K, const double & ALPHA, const double * A, const size_t & LDA, const double * B, const size_t & LDB, const double & BETA, double * C, const size_t & LDC) inline
Perform a matrix-matrix multiplication.
Perform the matrix-matrix multiplication
\[ C = \alpha \mathrm{op}(A) \mathrm{op}(B) + \beta \mathrm{op}(C) \]
where \(\mathrm{op}(A)\) represents either \(A\) or \(A^{T}\) (transpose of \(A\)).
LIBXSMM, which is much faster than BLAS for small matrices, can be called instead of BLAS by passing the template parameter true.
Parameters
TRANSA either 'N', 'T' or 'C', transposition of matrix A
TRANSB either 'N', 'T' or 'C', transposition of matrix B
M Number of rows in \(\mathrm{op}(A)\)
N Number of columns in \(\mathrm{op}(B)\) and \(\mathrm{op}(C)\)
K Number of columns in \(\mathrm{op}(A)\)
ALPHA specifies \(\alpha\)
A Matrix \(A\)
LDA Specifies first dimension of \(\mathrm{op}(A)\)
B Matrix \(B\)
LDB Specifies first dimension of \(\mathrm{op}(B)\)
BETA specifies \(\beta\)
C Matrix \(C\)
LDC Specifies first dimension of \(\mathrm{op}(C)\)
Template Parameters
UseLibXsmm if true then use LIBXSMM
References ASSERT.
Referenced by test_blas_asserts_for_bad_char::dgemm_error_transa_false(), test_blas_asserts_for_bad_char::dgemm_error_transb_false(), and Basis::lgl::linear_filter_matrix().
dgemm_< true >()
template<> void dgemm_< true > (const char & TRANSA, const char & TRANSB, const size_t & M, const size_t & N, const size_t & K, const double & ALPHA, const double * A, const size_t & LDA, const double * B, const size_t & LDB, const double & BETA, double * C, const size_t & LDC) inline
Perform a matrix-matrix multiplication.
Perform the matrix-matrix multiplication
\[ C = \alpha \mathrm{op}(A) \mathrm{op}(B) + \beta \mathrm{op}(C) \]
where \(\mathrm{op}(A)\) represents either \(A\) or \(A^{T}\) (transpose of \(A\)).
LIBXSMM, which is much faster than BLAS for small matrices, can be called instead of BLAS by passing the template parameter true.
Parameters
TRANSA either 'N', 'T' or 'C', transposition of matrix A
TRANSB either 'N', 'T' or 'C', transposition of matrix B
M Number of rows in \(\mathrm{op}(A)\)
N Number of columns in \(\mathrm{op}(B)\) and \(\mathrm{op}(C)\)
K Number of columns in \(\mathrm{op}(A)\)
ALPHA specifies \(\alpha\)
A Matrix \(A\)
LDA Specifies first dimension of \(\mathrm{op}(A)\)
B Matrix \(B\)
LDB Specifies first dimension of \(\mathrm{op}(B)\)
BETA specifies \(\beta\)
C Matrix \(C\)
LDC Specifies first dimension of \(\mathrm{op}(C)\)
Template Parameters
UseLibXsmm if true then use LIBXSMM
References ASSERT, and gsl::narrow_cast().
Referenced by test_blas_asserts_for_bad_char::dgemm_error_transa_true(), and test_blas_asserts_for_bad_char::dgemm_error_transb_true().
dgemv_()
void dgemv_ (const char & TRANS, const size_t & M, const size_t & N, const double & ALPHA, const double * A, const size_t & LDA, const double * X, const size_t & INCX, const double & BETA, double * Y, const size_t & INCY) inline
Perform a matrix-vector multiplication.
\[ y = \alpha \mathrm{op}(A) x + \beta y \]
where \(\mathrm{op}(A)\) represents either \(A\) or \(A^{T}\) (transpose of \(A\)).
Parameters
TRANS either 'N', 'T' or 'C', transposition of matrix A
M Number of rows in \(\mathrm{op}(A)\)
N Number of columns in \(\mathrm{op}(A)\)
ALPHA specifies \(\alpha\)
A Matrix \(A\)
LDA Specifies first dimension of \(\mathrm{op}(A)\)
X Vector \(x\)
INCX Specifies the increment for the elements of \(x\)
BETA Specifies \(\beta\)
Y Vector \(y\)
INCY Specifies the increment for the elements of \(y\)
References ASSERT.
Referenced by test_blas_asserts_for_bad_char::dgemv_error_trans().
formatted_string()
template<typename... Args> std::string formatted_string (const std::string & fmt, Args... args)
Format a string like printf.
Given a formatting string and arguments this returns the corresponding string. Similar to printf but using std::strings.
References std::snprintf().
info_from_build()
std::string info_from_build ()
Information about the version, date, host, git commit, and link time.
The information returned by this function is invaluable for identifying the version of the code used in a simulation, as well as which host, the date the code was compiled, and the time of linkage.
References spectre_version().
Referenced by main(), and RunTests::RunTests().
keys_of()
template<typename Map , typename std::enable_if_t< tt::is_maplike< Map >::value > * = nullptr> std::string keys_of (const Map & m) inline
Construct a string containing the keys of a map.
make_array() [1/2]
template<std::size_t size, typename T > constexpr std::array<std::decay_t<T>, size> make_array (T && value)
Helper class to initialize a std::array.
Template Parameters
size the length of the array
References make_array(), and SPECTRE_ALWAYS_INLINE.
make_array() [2/2]
template<typename T , typename... V, typename std::enable_if_t<(sizeof...(V) > 0> constexpr std::array<typename std::decay_t<T>, sizeof...(V) + 1> make_array (T && t, V &&... values)
Helper function to initialize a std::array with varying number of arguments.
References cpp17::conjunction_v.
make_deferred()
template<typename Fp , typename... Args> Deferred<Rt1> make_deferred (Fp f, Args &&... args)
Create a deferred function call object.
If creating a Deferred with a function object the call operator of the function object must be marked const currently. Since the function object will only be evaluated once there currently seems to be no reason to allow mutating call operators.
Example
The examples below use the following functions:
struct func {
  double operator()() const { return 8.2; }
};
double dummy() { return 6.7; }
struct func2 {
  double operator()(const double& t) const { return t; }
};
double lazy_function(const double t) { return 10.0 * t; }
To create a Deferred using a function object use:
  auto def = make_deferred(func{});
  CHECK(8.2 == def.get());
or using a regular function:
  auto def2 = make_deferred(dummy);
  CHECK(6.7 == def2.get());
It is also possible to pass Deferred objects to a deferred function call:
  auto def2 = make_deferred(func2{}, 6.82);
  auto def3 = make_deferred(lazy_function, def2);
  CHECK(68.2 == def3.get());
  CHECK(6.82 == def2.get());
in which case the first function will be evaluated just before the second function is evaluated.
Returns: Deferred object that will lazily evaluate the function
References std::make_shared().
Referenced by Deferred< Rt >::Deferred().
narrow()
template<class T , class U > T gsl::narrow (U u)
A checked version of narrow_cast() that ERRORs if the cast changed the value.
References ERROR, and gsl::narrow_cast().
narrow_cast()
template<class T , class U > constexpr T gsl::narrow_cast (U && u) noexcept
Cast u to a type T where the cast may result in narrowing.
Referenced by dgemm_< true >(), and gsl::narrow().
operator"" _st()
constexpr size_t operator"" _st (const unsigned long long n) inline
Defines the _st size_t suffix.
operator<<() [1/10]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::list< T > & v) inline
Output the items of a std::list.
operator<<() [2/10]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::vector< T > & v) inline
Output the items of a std::vector.
operator<<() [3/10]
template<typename T , size_t N> std::ostream& operator<< (std::ostream & os, const std::array< T, N > & a) inline
Output the items of a std::array.
operator<<() [4/10]
template<typename... Args> std::ostream& operator<< (std::ostream & os, const std::tuple< Args... > & t) inline
Stream operator for tuples.
operator<<() [5/10]
template<typename Map , typename std::enable_if_t< tt::is_maplike< Map >::value > * > std::ostream& operator<< (std::ostream & os, const Map & m) inline
Output all the key, value pairs of a map.
operator<<() [6/10]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::unordered_set< T > & v) inline
Output the items of a std::unordered_set.
operator<<() [7/10]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::set< T > & v) inline
Output the items of a std::unordered_set.
operator<<() [8/10]
template<typename T , typename std::enable_if_t< tt::is_streamable< std::ostream, T >::value > * > std::ostream& operator<< (std::ostream & os, const std::unique_ptr< T > & t) inline
Stream operator for std::unique_ptr.
operator<<() [9/10]
template<typename T , typename std::enable_if_t< tt::is_streamable< std::ostream, T >::value > * > std::ostream& operator<< (std::ostream & os, const std::shared_ptr< T > & t) inline
Stream operator for std::shared_ptr.
operator<<() [10/10]
template<typename T , typename U > std::ostream& operator<< (std::ostream & os, const std::pair< T, U > & t) inline
Stream operator for std::pair.
spectre_major_version()
int spectre_major_version ()
Returns major version.
spectre_minor_version()
int spectre_minor_version ()
Returns minor version.
spectre_patch_version()
int spectre_patch_version ()
Returns patch version.
spectre_version()
std::string spectre_version ()
Retrieve a string containing the current version of SpECTRE.
Referenced by info_from_build().