SpECTRE: Constant Expressions
Constant Expressions
Contains an assortment of constexpr functions.
Functions
template<typename T , std::enable_if_t< std::is_integral< T >::value and not std::is_same< bool, T >::value > * = nullptr>
constexpr T two_to_the (T n)
Compute 2 to the n for integral types.
constexpr size_t get_nth_bit (const size_t i, const size_t N)
Get the nth bit from the right, counting from zero.
template<typename T >
constexpr T square (const T &x)
Compute the square of x
template<typename T >
constexpr T cube (const T &x)
Compute the cube of x
template<int N, typename T >
decltype(auto) constexpr pow (const T &t)
Compute t^N where N is an integer (positive or negative)
template<typename Ls , std::enable_if_t< not tt::is_a_v< tmpl::list, tmpl::front< Ls >>> * = nullptr>
constexpr std::array< std::decay_t< decltype(tmpl::front< Ls >::value)>, tmpl::size< Ls >::value > make_array_from_list ()
Make an array from a typelist that holds std::integral_constant's all of which have the same value_type
constexpr size_t cstring_length (const char *str)
Compute the length of a const char* at compile time.
constexpr size_t cstring_hash (const char *str)
Compute a hash of a const char* at compile time.
template<size_t I, typename T , size_t Size>
constexpr std::array< std::decay_t< T >, Size > replace_at (const std::array< T, Size > &arr, T value)
Replace at compile time the Ith entry in the array with value
template<typename T , typename S , size_t size>
constexpr bool array_equal (const std::array< T, size > &lhs, const std::array< S, size > &rhs, const size_t i=0)
Check at compile time if two std::arrays are equal.
Detailed Description
Contains an assortment of constexpr functions.
Description
Contains an assortment of constexpr functions that are useful for metaprogramming, or efficient mathematical computations, such as exponentiating to an integer power, where the power is known at compile time.
Function Documentation
array_equal()
template<typename T , typename S , size_t size> constexpr bool array_equal (const std::array< T, size > & lhs, const std::array< S, size > & rhs, const size_t i = 0) inline
Check at compile time if two std::arrays are equal.
cstring_hash()
constexpr size_t cstring_hash (const char * str)
Compute a hash of a const char* at compile time.
cstring_length()
constexpr size_t cstring_length (const char * str)
Compute the length of a const char* at compile time.
cube()
template<typename T > constexpr T cube (const T & x)
Compute the cube of x
References pow(), and SPECTRE_ALWAYS_INLINE.
get_nth_bit()
constexpr size_t get_nth_bit (const size_t i, const size_t N)
Get the nth bit from the right, counting from zero.
Parameters
i the value to be acted on.
N which place to extract the bit
Returns: the value of the bit at that place.
make_array_from_list()
template<typename Ls , std::enable_if_t< not tt::is_a_v< tmpl::list, tmpl::front< Ls >>> * = nullptr> constexpr std::array<std::decay_t<decltype(tmpl::front<Ls>::value)>, tmpl::size<Ls>::value> make_array_from_list () inline
Make an array from a typelist that holds std::integral_constant's all of which have the same value_type
Template Parameters
Ls the typelist of std::integral_constant's
Returns: array of integral values from the typelist
Referenced by make_array_from_list().
pow()
template<int N, typename T > decltype(auto) constexpr pow (const T & t)
Compute t^N where N is an integer (positive or negative)
Warning
If passing an integer this will do integer arithmatic, e.g. pow<-10>(2) == 0
Template Parameters
N the integer power being raised to in t^N
Parameters
t the value being exponentiated
Returns: value t^N of type T
Referenced by cube(), DataVector::erfc(), and DataVector::pow().
replace_at()
template<size_t I, typename T , size_t Size> constexpr std::array<std::decay_t<T>, Size> replace_at (const std::array< T, Size > & arr, T value) inline
Replace at compile time the Ith entry in the array with value
square()
template<typename T > constexpr T square (const T & x)
Compute the square of x
two_to_the()
template<typename T , std::enable_if_t< std::is_integral< T >::value and not std::is_same< bool, T >::value > * = nullptr> constexpr T two_to_the (T n)
Compute 2 to the n for integral types.
Parameters
n the power of two to compute.
Returns: 2^n