SpECTRE: Basis::lgl Namespace Reference
Basis::lgl Namespace Reference
Numerical Algorithms
Functions for using Legendre-Gauss-Lobatto basis.
Functions
const DataVector & collocation_points (size_t number_of_pts)
Collocation points.
const DataVector & quadrature_weights (size_t number_of_pts)
Quadrature weights.
const Matrix & differentiation_matrix (size_t number_of_pts)
Matrix used to compute the first derivative of a function.
const Matrix & grid_points_to_spectral_matrix (size_t number_of_pts)
Matrix used to compute spectral coefficients of a function.
const Matrix & spectral_to_grid_points_matrix (size_t number_of_pts)
Matrix used to compute function at the collocation points from its spectral coefficients.
const Matrix & linear_filter_matrix (size_t number_of_pts)
Matrix used to linearize a function.
template<typename T >
Matrix interpolation_matrix (size_t number_of_pts, const T &target_points)
Matrix to interpolate to a set of target points.
Variables
static const size_t maximum_number_of_pts = 12
Maximum number of allowed collocation points for LGL basis.
Detailed Description
Functions for using Legendre-Gauss-Lobatto basis.
Function Documentation
collocation_points()
const DataVector & Basis::lgl::collocation_points (size_t number_of_pts)
Collocation points.
Parameters
number_of_pts number of collocation points
differentiation_matrix()
const Matrix & Basis::lgl::differentiation_matrix (size_t number_of_pts)
Matrix used to compute the first derivative of a function.
Parameters
number_of_pts number of collocation points
References ASSERT, and maximum_number_of_pts.
grid_points_to_spectral_matrix()
const Matrix & Basis::lgl::grid_points_to_spectral_matrix (size_t number_of_pts)
Matrix used to compute spectral coefficients of a function.
Parameters
number_of_pts number of collocation points
References ASSERT, and maximum_number_of_pts.
Referenced by linear_filter_matrix().
interpolation_matrix()
template<typename T > Matrix Basis::lgl::interpolation_matrix (size_t number_of_pts, const T & target_points)
Matrix to interpolate to a set of target points.
Warning
It is expected but not checked that the target points are inside the domain.
Parameters
number_of_pts number of collocation points
target_points the points to interpolate to
References ASSERT, and maximum_number_of_pts.
linear_filter_matrix()
const Matrix & Basis::lgl::linear_filter_matrix (size_t number_of_pts)
Matrix used to linearize a function.
Filters out all except the lowest two modes.
Parameters
number_of_pts number of collocation points
References ASSERT, Matrix::data(), dgemm_(), grid_points_to_spectral_matrix(), maximum_number_of_pts, and spectral_to_grid_points_matrix().
quadrature_weights()
const DataVector & Basis::lgl::quadrature_weights (size_t number_of_pts)
Quadrature weights.
Parameters
number_of_pts number of collocation points
spectral_to_grid_points_matrix()
const Matrix & Basis::lgl::spectral_to_grid_points_matrix (size_t number_of_pts)
Matrix used to compute function at the collocation points from its spectral coefficients.
Parameters
number_of_pts number of collocation points
References ASSERT, and maximum_number_of_pts.
Referenced by linear_filter_matrix().
Variable Documentation
maximum_number_of_pts
const size_t Basis::lgl::maximum_number_of_pts = 12 static
Maximum number of allowed collocation points for LGL basis.
Referenced by differentiation_matrix(), grid_points_to_spectral_matrix(), interpolation_matrix(), linear_filter_matrix(), and spectral_to_grid_points_matrix().