SpECTRE: test_blas_asserts_for_bad_char Namespace Reference
test_blas_asserts_for_bad_char Namespace Reference
Functions
void dgemm_error_transa_false ()
void dgemm_error_transb_false ()
void dgemm_error_transa_true ()
void dgemm_error_transb_true ()
void dgemv_error_trans ()
Function Documentation
dgemm_error_transa_false()
void test_blas_asserts_for_bad_char::dgemm_error_transa_false () inline
References dgemm_().
dgemm_error_transa_true()
void test_blas_asserts_for_bad_char::dgemm_error_transa_true () inline
References dgemm_< true >().
dgemm_error_transb_false()
void test_blas_asserts_for_bad_char::dgemm_error_transb_false () inline
References dgemm_().
dgemm_error_transb_true()
void test_blas_asserts_for_bad_char::dgemm_error_transb_true () inline
References dgemm_< true >().
dgemv_error_trans()
void test_blas_asserts_for_bad_char::dgemv_error_trans () inline
References dgemv_().