SpECTRE: src/Domain/SegmentId.hpp File Reference
SegmentId.hpp File Reference
Defines class SegmentId.
#include <cstdint>
#include <iosfwd>
#include <pup.h>
#include "Domain/Side.hpp"
#include "ErrorHandling/Assert.hpp"
#include "Utilities/ConstantExpressions.hpp"
Classes
class SegmentId
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
Functions
std::ostream & operator<< (std::ostream &os, const SegmentId &id)
Output operator for SegmentId.
bool operator== (const SegmentId &lhs, const SegmentId &rhs)
Equivalence operator for SegmentId.
bool operator!= (const SegmentId &lhs, const SegmentId &rhs)
Inequivalence operator for SegmentId.
size_t hash_value (const SegmentId &s) noexcept
Detailed Description
Defines class SegmentId.
Function Documentation
hash_value()
size_t hash_value (const SegmentId & s) noexcept
Referenced by SegmentId::endpoint().
operator!=()
bool operator!= (const SegmentId & lhs, const SegmentId & rhs) inline
Inequivalence operator for SegmentId.
Referenced by SegmentId::midpoint().
operator<<()
std::ostream& operator<< (std::ostream & os, const SegmentId & id)
Output operator for SegmentId.
Referenced by SegmentId::midpoint().
operator==()
bool operator== (const SegmentId & lhs, const SegmentId & rhs) inline
Equivalence operator for SegmentId.
References SegmentId::index(), and SegmentId::refinement_level().
Referenced by SegmentId::midpoint().