SpECTRE: src/DataStructures/Matrix.cpp File Reference
Matrix.cpp File Reference
#include "Matrix.hpp"
#include <ostream>
#include <pup.h>
#include <pup_stl.h>
Functions
std::ostream & operator<< (std::ostream &os, const Matrix &m)
Stream operator for Matrix.
bool operator== (const Matrix &lhs, const Matrix &rhs)
Equivalence operator for Matrix.
bool operator!= (const Matrix &lhs, const Matrix &rhs)
Inequivalence operator for Matrix.
Function Documentation
operator!=()
bool operator!= (const Matrix & lhs, const Matrix & rhs)
Inequivalence operator for Matrix.
operator<<()
std::ostream& operator<< (std::ostream & os, const Matrix & m)
Stream operator for Matrix.
References Matrix::columns(), and Matrix::rows().
operator==()
bool operator== (const Matrix & lhs, const Matrix & rhs)
Equivalence operator for Matrix.
References Matrix::begin(), Matrix::columns(), Matrix::end(), std::equal(), and Matrix::rows().