var searchData=
[
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['value',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/utility/optional/value.html',1,'std::optional::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::pmr::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::pmr::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::pmr::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::pmr::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or()'],['http://en.cppreference.com/w/cpp/utility/optional/value_or.html',1,'std::optional::value_or()']]],
  ['valueless_5fby_5fexception',['valueless_by_exception',['http://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',1,'std::variant']]],
  ['variables',['Variables',['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#a8f9fc58967b364580cfe2b449f0d8bc8',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables()=default'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#a056fa854eafb85c0bdef14a542fa3832',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(size_t number_of_grid_points, double value=std::numeric_limits&lt; double &gt;::signaling_NaN())'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#adc2cdd45ca2c59f1f981a8bab7e224f8',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(Variables &amp;&amp;rhs) noexcept=default'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#a0dc444758064da9e4385b4108a4dc944',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(const Variables &amp;rhs)'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#aed662abe78488e4308eae33f925799ae',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(const blaze::Vector&lt; VT, VF &gt; &amp;expression)']]],
  ['variant',['variant',['http://en.cppreference.com/w/cpp/utility/variant/variant.html',1,'std::variant']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::pmr::vector::vector()'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vfprintf',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['visit',['visit',['http://en.cppreference.com/w/cpp/utility/variant/visit.html',1,'std']]],
  ['volume_5foffset',['volume_offset',['../classSliceIterator.html#ae81dd0b41c36f65c851fb16e847b41cf',1,'SliceIterator']]],
  ['vprintf',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
